=== a-thaler/yaas-platform-info-service/rootfs/var/nginx/meta/schemas/info_entity.json
{
    "$schema": "http://json-schema.org/draft-04/schema", 
    "required": [
        "city", 
        "network", 
        "country", 
        "region", 
        "position", 
        "yaas"
    ], 
    "type": "object", 
    "properties": {
        "city": {
            "required": [
                "postal", 
                "name"
            ], 
            "type": "object", 
            "properties": {
                "postal": {
                    "type": "string"
                }, 
                "name": {
                    "type": "string"
                }
            }
        }, 
        "network": {
            "required": [
                "access", 
                "ip"
            ], 
            "type": "object", 
            "properties": {
                "access": {
                    "type": "string"
                }, 
                "ip": {
                    "type": "string"
                }
            }
        }, 
        "country": {
            "required": [
                "code", 
                "name"
            ], 
            "type": "object", 
            "properties": {
                "code": {
                    "type": "string"
                }, 
                "name": {
                    "type": "string"
                }
            }
        }, 
        "region": {
            "required": [
                "timezone", 
                "name"
            ], 
            "type": "object", 
            "properties": {
                "timezone": {
                    "required": [
                        "_link_", 
                        "name"
                    ], 
                    "type": "object", 
                    "properties": {
                        "_link_": {
                            "type": "string"
                        }, 
                        "name": {
                            "type": "string"
                        }
                    }
                }, 
                "name": {
                    "type": "string"
                }
            }
        }, 
        "position": {
            "required": [
                "latitude", 
                "longitude"
            ], 
            "type": "object", 
            "properties": {
                "latitude": {
                    "type": "number"
                }, 
                "longitude": {
                    "type": "number"
                }
            }
        }, 
        "yaas": {
            "required": [
                "language", 
                "market"
            ], 
            "type": "object", 
            "properties": {
                "market": {
                    "required": [
                        "_link_", 
                        "_redirect_", 
                        "id"
                    ], 
                    "type": "object", 
                    "properties": {
                        "_link_": {
                            "type": "string"
                        }, 
                        "_redirect_": {
                            "type": "string"
                        }, 
                        "id": {
                            "type": "string"
                        }
                    }
                }, 
                "language": {
                    "required": [
                        "default", 
                        "official", 
                        "preferred"
                    ], 
                    "type": "object", 
                    "properties": {
                        "default": {
                            "type": "string"
                        }, 
                        "official": {
                            "type": "string"
                        }, 
                        "preferred": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== a-thaler/yaas-platform-info-service/rootfs/var/nginx/meta/examples/info.json
{
  "country": {
    "code": "DE",
    "name": "Germany"
  },
  "city": {
    "name": "Hamburg",
    "postal": "20099"
  },
  "network": {
    "ip": "91.32.146.214",
    "access": "unrestricted"
  },
  "position": {
    "latitude": 53.5553,
    "longitude": 9.995
  },
  "yaas": {
    "market": {
      "id": "DE",
      "_link_": "https://api.eu.yaas.io/hybris/ypi/v1/markets/DE",
      "_redirect_": "https://market.yaas.io/de"
    },
    "language": {
      "preferred": "de",
      "official": "de-DE",
      "default": "de"
    }
  },
  "region": {
    "name": "Hamburg",
    "timezone": {
      "name": "Europe/Berlin",
      "_link_": "https://api.eu.yaas.io/hybris/ypi/v1/timezone/Europe/Berlin"
    }
  }
}
