=== a-thaler/yaas-platform-info-service/rootfs/var/nginx/meta/schemas/market_entity.json
{
    "$schema": "http://json-schema.org/draft-04/schema", 
    "required": [
        "description", 
        "billing", 
        "url", 
        "region", 
        "links", 
        "locale", 
        "_link_", 
        "timezone", 
        "id", 
        "name"
    ], 
    "type": "object", 
    "properties": {
        "billing": {
            "required": [
                "currency", 
                "vendor", 
                "pricing"
            ], 
            "type": "object", 
            "properties": {
                "currency": {
                    "type": "string"
                }, 
                "vendor": {
                    "type": "string"
                }, 
                "pricing": {
                    "type": "string"
                }
            }
        }, 
        "description": {
            "type": "string"
        }, 
        "links": {
            "required": [
                "terms", 
                "copyright", 
                "privacy", 
                "contract", 
                "agreement_terms", 
                "api", 
                "impressum"
            ], 
            "type": "object", 
            "properties": {
                "terms": {
                    "type": "string"
                }, 
                "copyright": {
                    "type": "string"
                }, 
                "privacy": {
                    "type": "string"
                }, 
                "contract": {
                    "type": "string"
                }, 
                "agreement_terms": {
                    "type": "string"
                }, 
                "api": {
                    "type": "string"
                }, 
                "impressum": {
                    "type": "string"
                }
            }
        }, 
        "url": {
            "type": "string"
        }, 
        "region": {
            "required": [
                "_link_", 
                "id"
            ], 
            "type": "object", 
            "properties": {
                "_link_": {
                    "type": "string"
                }, 
                "id": {
                    "type": "string"
                }
            }
        }, 
        "locale": {
            "required": [
                "languages", 
                "default", 
                "official"
            ], 
            "type": "object", 
            "properties": {
                "languages": {
                    "items": {
                        "type": "string"
                    }, 
                    "type": "array"
                }, 
                "default": {
                    "type": "string"
                }, 
                "official": {
                    "type": "string"
                }
            }
        }, 
        "_link_": {
            "type": "string"
        }, 
        "timezone": {
            "required": [
                "_link_", 
                "name"
            ], 
            "type": "object", 
            "properties": {
                "_link_": {
                    "type": "string"
                }, 
                "name": {
                    "type": "string"
                }
            }
        }, 
        "id": {
            "type": "string"
        }, 
        "name": {
            "type": "string"
        }
    }
}

=== a-thaler/yaas-platform-info-service/rootfs/var/nginx/meta/examples/market.json
{
  "id": "US",
  "name": "YaaS United States Market",
  "description": "SAP-Hybris YaaS Market United States of America",
  "_link_": "https://api.eu.yaas.io/hybris/ypi/v1/markets/US",
  "url": "https://market.yaas.io/us",
  "locale": {
    "languages": [
      "en",
      "de"
    ],
    "official": "en-US",
    "default": "en"
  },
  "timezone": {
    "name": "America/New_York",
    "_link_": "https://api.eu.yaas.io/hybris/ypi/v1/timezone/America/New_York"
  },
  "region": {
    "_link_": "https://api.eu.yaas.io/hybris/ypi/v1/regions/US",
    "id": "US"
  },
  "billing": {
    "currency": "USD",
    "pricing": "usPriceGroup",
    "vendor": "sapamerica"
  },
  "links": {
    "impressum": "https://go.sap.com/about/legal/impressum.html",
    "copyright": "https://go.sap.com/about/legal/copyright.html",
    "privacy": "https://go.sap.com/about/legal/privacy.html",
    "terms": "https://www.yaas.io/legal/sap-hybris-as-a-service-account-terms-of-use_v2.html",
    "contract": "https://www.yaas.io/legal/sap-hybris-as-a-service-organization-terms-of-use_v1.html",
    "agreement_terms": "https://www.yaas.io/legal/SAP_Hybris_as_a_Service_Terms-of-use_usEN_v10-2016.pdf",
    "api": "https://api.us.yaas.io"
  }
}
