=== a-thaler/yaas-platform-info-service/rootfs/var/nginx/meta/schemas/network_entity.json
{
    "$schema": "http://json-schema.org/draft-04/schema", 
    "required": [
        "networks", 
        "continent", 
        "id", 
        "name"
    ], 
    "type": "object", 
    "properties": {
        "id": {
            "type": "string"
        }, 
        "networks": {
            "required": [
                "IPv4", 
                "IPv6"
            ], 
            "type": "object", 
            "properties": {
                "IPv4": {
                    "items": {
                        "type": "string"
                    }, 
                    "type": "array"
                }, 
                "IPv6": {
                    "items": {
                        "type": "string"
                    }, 
                    "type": "array"
                }
            }
        }, 
        "name": {
            "type": "string"
        }, 
        "continent": {
            "required": [
                "name", 
                "id"
            ], 
            "type": "object", 
            "properties": {
                "name": {
                    "type": "string"
                }, 
                "id": {
                    "type": "string"
                }
            }
        }
    }
}

=== a-thaler/yaas-platform-info-service/rootfs/var/nginx/meta/examples/network.json
{
  "id": "LU",
  "name": "Luxembourg",
  "continent": {
    "name": "Europe",
    "id": "EU"
  },
  "networks": {
    "IPv6": [
      "2001:678:1b::/48",
      "2001:67c:2aa0::/48",
      "2001:7e8::/32",
      "2001:a18::/29",
      "2a0b:ac00::/29"
    ],
    "IPv4": [
      "5.23.10.0/24",
      "5.159.216.0/21",
      "5.196.183.184/30",
      "17.72.104.0/24",
      "31.6.52.0/24",
      "77.70.142.192/26",
      "78.141.128.0/18",
      "79.142.78.0/24",
      "80.64.144.0/20",
      "80.90.32.0/19",
      "80.92.64.0/19",
      "80.246.96.0/20",
      "80.255.164.0/22",
      "80.255.168.0/21",
      "81.92.238.0/25",
      "81.92.238.128/26",
      "89.44.168.0/21",
      "89.106.200.0/21",
      "91.142.129.0/24",
      "92.42.176.0/21",
      "92.71.68.0/23",
      "92.223.80.0/21",
      "141.101.132.128/25",
      "146.0.58.0/23",
      "146.0.128.0/18",
      "146.0.212.0/22",
      "158.169.148.0/23",
      "158.169.151.0/24",
      "185.66.105.0/24",
      "185.71.56.0/22",
      "185.80.124.0/22",
      "185.94.0.0/22",
      "188.42.168.0/21",
      "192.237.99.0/26",
      "193.9.128.0/20",
      "193.9.144.0/22",
      "193.19.112.0/23",
      "194.117.116.48/30",
      "194.117.122.232/32",
      "195.51.50.32/29",
      "195.61.227.0/24",
      "206.182.53.128/26",
      "206.182.90.0/25",
      "212.63.165.180/30",
      "212.63.169.136/30",
      "217.77.242.30/32",
      "217.197.96.0/20"
    ]
  }
}
